filterMblogKey:
  status:
    created_at: "4"
    source_tag_struct: "1"
    idstr: "4"
    text: "4"
    source: "4"
    custom_fields: "1"
    text_source: "4"
    source_scheme: "4"
    favorited: "3"
    truncated: "3"
    in_reply_to_status_id: "4"
    in_reply_to_user_id: "4"
    in_reply_to_screen_name: "4"
    function_limit: "2"
    closed_topic: "3"
    reposts_count: "2"
    comments_count: "2"
    attitudes_count: "2"
    attitudes_tips: "4"
    attitudes_animation: "2"
    schedule_id: "4"
    schedule_at: "4"
    stream_entry_id: "4"
    attitudes_status: "2"
    like_attitude_type: "2"
    show_attitude_bar: "2"
    enable_comment_guide: "3"
    comment_guide_type: "2"
    show_comment_guide_flag: "2"
    is_hide_repost: "2"
    is_hide_comment: "2"
    is_hide_like: "2"
    trend_status_source_type: "2"
    is_vote: "2"
    click_actionlog: "1"
    mlevel: "2"
    function_disable_prompt: "1"
    source_type: "2"
    visible: "1"
    distance: "2"
    scheme: "4"
    mark: "4"
    extend_info: "1"
    show_attitude_count: "2"
    mblogtype: "2"
    mblogtypename: "4"
    shared_url: "4"
    shared_count: "2"
    extern_safe: "2"
    complaint: "1"
    recom_state: "2"
    deleted_btn_text: "4"
    page_info: "1"
    mix_media_info: "1"
    thumbnail_pic: "4"
    mblog_menu_new_style: "2"
    user: "1"
    screen_name_suffix_new_sence: "2"
    show_rt_region_button: "2"
    red_coupon: "1"
    geo: "1"
    pic_infos: "1"
    mini_pic_show_type: "2"
    number_display_strategy: "1"
    retweeted_status: "1"
    parent_status: "1"
    title: "1"
    pic_bg_new: "4"
    pic_bg_type: "2"
    pic_bg_scheme: "4"
    ori_mid: "4"
    action_button_icon_dic: "1"
    pic_bg_text: "4"
    rid: "4"
    is_disable_highlight: "2"
    is_controlled_by_server: "2"
    timestamp_text: "4"
    readtimetype: "4"
    mblog_show_union_info: "2"
    comment_summary: "1"
    forward_summary: "1"
    like_summary: "1"
    like_attention_summary: "1"
    source_allowclick: "2"
    promotion_info: "1"
    promotion: "1"
    can_edit: "3"
    version: "2"
    preload_type: "2"
    show_additional_indication: "2"
    additional_indication_tips: "4"
    additional_indication_icon_url: "4"
    preload_data: "1"
    continue_tag: "1"
    has_extra_text: "3"
    isLongText: "3"
    longText: "1"
    topRightButtonType: "2"
    extra_button_info: "1"
    is_show_bulletin: "2"
    need_approval_comment: "2"
    update_time: "4"
    positive_recom_flag: "2"
    positive_recom_type: "4"
    hot_ext: "4"
    ext_feature: "1"
    analysis_extra: "4"
    comment_manage_info: "1"
    more_info: "1"
    pending_approval_count: "2"
    text_max_lines: "2"
    pic_url: "4"
    is_paid: "3"
    mblog_vip_type: "2"
    attitudenum: "2"
    attitudeid: "2"
    edit_config: "1"
    local_force_horizontal: "3"
    content_auth: "2"
    content_auth_info: "1"
    content_auth_suffix: "1"
    full_text: "4"
    obj_ext: "4"
    most_attitude_type: "2"
    hide_from_prefix: "2"
    reward_scheme: "4"
    hide_flag: "2"
    is_fold: "2"
    mblog_lines: "2"
    attitude_dynamic_adid: "4"
    ad_info: "1"
    like_animation_adid: "4"
    section_id: "4"
    ad_object: "1"
    sendPoint: "1"
    style: "1"
    pic_num: "2"
    special_follow_menu_show: "2"
    cancel_follow_attention: "1"
    is_oasis_weibo: "2"
    video_info: "1"
    spotlights: "1"
    index: "2"
    gid: "4"
    hide_bottom_buttons: "2"
    force_card_view: "2"
    share_repost_type: "2"
    feature_type: "4"
    goods_oid: "4"
    easter_egg: "1"
    comment_guide_placeholder: "4"
    push_callback: "1"
    header_info: "1"
    object_info: "1"
    title_source: "1"
    topic_id: "4"
    hidebtns: "2"
    flowCategory: "4"
    flowItemExt: "1"
    flowItemIdType: "2"
    flowItemTrigger: "1"
    comment_guide_level: "2"
    flowItemType: "4"
    new_come: "2"
    can_reprint: "3"
    photo_callback_params: "4"
    reprinted_status: "1"
    reward_info: "1"
    share_limit: "3"
    campaign_info: "1"
    region_name: "4"
    region_opt: "2"
    like_video_animation: "1"
    is_reward_bg: "3"
    button_extra_info: "1"
    stamp_info: "1"
    showHotReviewId: "4"
    mid: "4"
    author_mid: "4"
    object_id: "4"
  video_info:
    type: "2"
    skip_bubble_guide: "2"
    support_landscape_mode: "2"
    play_start_time: "2"
    bell_state: "2"
    auto_play_flag: "2"
    support_shrink: "2"
    isInsertNextVideo: "2"
    music: "1"
    sub_info: "1"
    follow_enhance: "1"
    content_info: "1"
    bottom_banner: "1"
    ad_info: "1"
    customized: "1"
    duration_info: "1"
    action_log: "1"
    recom_ext: "1"
    timestamp: "1"
    reprinted_status: "1"
    play_core_area: "1"
    toast: "1"
    cover_decor_icon: "1"
    float_info: "1"
    video_order: "1"
    pay_playlist_video: "1"
    guide_info: "1"
    action_info: "1"
    mini_spotlights: "1"
    follow_style: "1"
    bullet_screen: "1"
    bullet_screen_config: "1"
    barrage_config: "1"
    redpacket_slide_guide: "1"
    interactive: "1"
    twinkle_guide: "1"
    video_reward: "1"
    async_info: "1"
    forward_redpacket_info: "1"
    pay_album_info: "1"
    media_play_info: "1"
    bottom_info: "1"
    vote_info: "1"
    vote_object: "1"
    feedback_recom: "1"
    live_data: "1"
    user: "1"
    display_strategy: "1"
    effect_rank: "1"
    mask: "1"
    title_tag: "1"
    sort_title: "4"
    force_reload: "4"
    media_id: "4"
    cursor_id: "4"
    diversion_mid: "4"
    scheme_v2: "4"
    photo_together_scheme: "4"
    no_mark_download_url: "4"
    common_action_log: "4"
    source_info: "4"
    clear_screen: "3"
  media_info:
    next_title: "4"
    object_category: "4"
    object_type: "4"
    object_id: "4"
    media_id: "4"
    protocol: "4"
    ad_video_type: "4"
    id: "4"
    page_id: "4"
    mblogid: "4"
    unique_id: "4"
    log_video_uniqueId: "4"
    uuid: "4"
    playlist_id: "4"
    scid: "4"
    storage_type: "4"
    mContent: "4"
    video_tail_info: "4"
    video_tail_info_vvs_vplus: "4"
    scheme: "4"
    search_scheme: "4"
    reprinted_original_user: "4"
    name: "4"
    notice_danmaku: "4"
    hint: "4"
    stream_url: "4"
    stream_url_hd: "4"
    mp4_sd_url: "4"
    mp4_hd_url: "4"
    mp4_sd_url_extension: "4"
    mp4_hd_url_extension: "4"
    hevc_mp4_hd: "4"
    hevc_mp4_ld: "4"
    mp4_720p_mp4: "4"
    mp4_720p_mp4_extension: "4"
    hevc_mp4_720p: "4"
    mp4_1080p_mp4: "4"
    hevc_mp4_1080p: "4"
    mp4_1080p_mp4_extension: "4"
    mp4_1440p_mp4: "4"
    hevc_mp4_1440p: "4"
    mp4_1440p_mp4_extension: "4"
    mp4_2160p_mp4: "4"
    hevc_mp4_2160p: "4"
    mp4_2160p_mp4_extension: "4"
    h5_url: "4"
    video_local_path: "4"
    ssig_updated_url: "4"
    online_users: "4"
    video_feed_title: "4"
    video_feed_actionbar_bg: "4"
    video_feed_actionbar_bg_status: "4"
    open_scheme: "4"
    author_mid: "4"
    author_name: "4"
    video_orientation: "4"
    ad_source: "4"
    first_level_channel_name: "4"
    second_level_channel_name: "4"
    live_source_icon: "4"
    h265_mp4_ld: "4"
    h265_mp4_hd: "4"
    video_title: "4"
    video_source: "4"
    kol_title: "4"
    replay_ld: "4"
    beint_collection: "2"
    is_subscribed: "2"
    is_contribution: "2"
    is_short_video: "2"
    play_loop_type: "2"
    ad_type: "2"
    forward_strategy: "2"
    interactive_video: "2"
    hide_more: "2"
    autoplay: "2"
    has_recommend_video: "2"
    is_keep_current_mblog: "2"
    is_ad_downloaded: "2"
    is_filter_duplicated: "2"
    online_users_number: "2"
    prefetch_type: "2"
    prefetch_size: "2"
    touch_quit: "2"
    video_feed_show_custom_bg: "2"
    video_rank: "2"
    author_verified_type: "2"
    video_unmute: "2"
    live_source: "2"
    hide_video_bottom: "2"
    show_progress_bar: "2"
    ttl: "2"
    videoExpiredTime: "2"
    playTime: "2"
    display_duration: "2"
    origin_total_bitrate: "2"
    live_replay_counts: "2"
    real_chatroom_users: "2"
    live_start_time: "2"
    live_replay_duration: "2"
    prevue_number: "2"
    music: "1"
    bottom_banner: "1"
    render_data: "1"
    scrubber_preview: "1"
    profile_video: "1"
    media_ad_overlayer: "1"
    media_ad_float: "1"
    collection_info: "1"
    author_info: "1"
    interactive_comment: "1"
    top_label: "1"
    top_right_tips: "1"
    back_paster_info: "1"
    video_download_strategy: "1"
    extra_info: "1"
    banner: "1"
    hot_tag: "1"
    ad_live_actionlog: "1"
    isForceAutoPlay: "3"
    isVideoTextExpanded: "3"
    isCompleteVideoUpdated: "3"
    isCommentVideo: "3"

search_channel_scenes:
  data:
    - "102803_ctg1_1780_-_ctg1_1780"
    - "102803_ctg1_1790_-_ctg1_1790"
    - "232660"
    - "231230_-_discover_-_index"
    - "232300_cardlist_discover_games"
    - "232727"
    - "102803_ctg1_1770_-_ctg1_1770"
    - "232858"

search_finder:
  flowPin:
    switch: "1"
    index: "6"

mini_flow:
  load_info:
    switch_title_mini: "        "
    switch_btn_title_mini: "精简模式"
    switch_title_classical: "        "
    switch_btn_title_classical: "标准模式"

icons_replace_config:
  version_limit: ">=C60"
